name: 'Release Notes'
description: 'Create release notes from pull request description'
author: 'Nicolas Filippelli'
inputs:
  GITHUB_TOKEN:
    description: "User token of service account."
    required: true
  JIRA_ISSUE_URL:
    description: "Link to Jira issue."
    required: true
outputs:
  RELEASE_NOTES:
    description: "Release notes."
runs:
  using: 'node12'
  main: 'dist/index.js'
